### PR TITLE
Return number of tip descendants in arguson

### PR DESCRIPTION
**Pull request by josephwb**
As requested by @jimallman. Regards https://github.com/OpenTreeOfLife/treemachine/issues/63

Gratuitous emoji: :collision:

### CODE REVIEW

**Comment by josephwb** [comment]
Example call:
```
curl 'https://devapi.opentreeoflife.org/treemachine/v1/getSyntheticTree' -H 'Content-Type: application/json' --data-binary '{"format":"arguson","maxDepth":"3","subtreeNodeID":"696701"}'
```
Response:
```json
{
  "name" : "Aves",
  "nodeid" : 696701,
  "children" : [ {
    "nTipDescendants" : 77,
    "taxSource" : "ncbi:8783",
    "children" : [ {
      "nTipDescendants" : 73,
      "children" : [ {
        "nTipDescendants" : 65,
        "hasChildren" : true,
        "name" : "",
        "supportedBy" : [ "pg_420_522_07054f960e6a5d42660af2bdda2fcc0a26120d71", "pg_2926_6757_a2c48df995ddc9fd208986c3d4225112550c8452" ],
        "nodeid" : 2710468,
        "descendantNameList" : [ "Casuariiformes", "Tinamiformes" ],
        "nleaves" : 0
      }, {
        "nTipDescendants" : 8,
        "taxSource" : "ncbi:8792,irmng:12386",
        "hasChildren" : true,
        "name" : "Rheiformes",
        "ottId" : "829553",
        "supportedBy" : [ "pg_420_522_07054f960e6a5d42660af2bdda2fcc0a26120d71", "pg_2926_6757_a2c48df995ddc9fd208986c3d4225112550c8452", "taxonomy" ],
        "nodeid" : 696703,
        "taxRank" : "order",
        "nleaves" : 0
      } ],
      "name" : "",
      "supportedBy" : [ "pg_420_522_07054f960e6a5d42660af2bdda2fcc0a26120d71", "pg_2926_6757_a2c48df995ddc9fd208986c3d4225112550c8452" ],
      "nodeid" : 2710467,
      "nleaves" : 2
    }, {
      "nTipDescendants" : 4,
      "taxSource" : "ncbi:8798,gbif:725,irmng:12031",
      "children" : [ {
        "nTipDescendants" : 4,
        "taxSource" : "ncbi:8799,gbif:9349,irmng:105097",
        "hasChildren" : true,
        "name" : "Struthionidae",
        "ottId" : "857849",
        "supportedBy" : [ "taxonomy" ],
        "nodeid" : 696781,
        "taxRank" : "family",
        "nleaves" : 0
      } ],
      "name" : "Struthioniformes",
      "ottId" : "857847",
      "supportedBy" : [ "pg_420_522_07054f960e6a5d42660af2bdda2fcc0a26120d71", "pg_2926_6757_a2c48df995ddc9fd208986c3d4225112550c8452", "taxonomy" ],
      "nodeid" : 696780,
      "taxRank" : "order",
      "nleaves" : 1
    } ],
    "name" : "Palaeognathae",
    "ottId" : "81443",
    "supportedBy" : [ "taxonomy" ],
    "nodeid" : 696702,
    "taxRank" : "superorder",
    "nleaves" : 3
  }, {
    "nTipDescendants" : 14436,
    "taxSource" : "ncbi:8825",
    "children" : [ {
      "nTipDescendants" : 13409,
      "children" : [ {
        "nTipDescendants" : 1,
        "taxSource" : "gbif:4966561",
        "hasChildren" : true,
        "name" : "Parvigruidae",
        "ottId" : "3600055",
        "supportedBy" : [ "taxonomy" ],
        "nodeid" : 715030,
        "taxRank" : "family",
        "nleaves" : 0
      }, {
        "nTipDescendants" : 1161,
        "hasChildren" : true,
        "name" : "",
        "supportedBy" : [ "pg_420_522_07054f960e6a5d42660af2bdda2fcc0a26120d71" ],
        "nodeid" : 2600239,
        "descendantNameList" : [ "Columbiformes", "Steatornithidae" ],
        "nleaves" : 0
      }, {
        "nTipDescendants" : 12248,
        "hasChildren" : true,
        "name" : "",
        "supportedBy" : [ "pg_420_522_07054f960e6a5d42660af2bdda2fcc0a26120d71" ],
        "nodeid" : 2600236,
        "descendantNameList" : [ "Musophagiformes", "Sagittariidae" ],
        "nleaves" : 0
      } ],
      "name" : "",
      "supportedBy" : [ "pg_420_522_07054f960e6a5d42660af2bdda2fcc0a26120d71" ],
      "nodeid" : 2600255,
      "nleaves" : 3
    }, {
      "nTipDescendants" : 703,
      "taxSource" : "ncbi:1549675",
      "children" : [ {
        "nTipDescendants" : 451,
        "taxSource" : "ncbi:8976,worms:225848,gbif:723,irmng:11922",
        "hasChildren" : true,
        "name" : "Galliformes",
        "ottId" : "837585",
        "supportedBy" : [ "taxonomy" ],
        "nodeid" : 697189,
        "taxRank" : "order",
        "nleaves" : 0
      }, {
        "nTipDescendants" : 252,
        "taxSource" : "ncbi:8826,worms:2681,gbif:1108,irmng:10908",
        "hasChildren" : true,
        "name" : "Anseriformes",
        "ottId" : "241841",
        "supportedBy" : [ "taxonomy" ],
        "nodeid" : 697807,
        "taxRank" : "order",
        "nleaves" : 0
      } ],
      "name" : "Galloanserae",
      "ottId" : "5779231",
      "supportedBy" : [ "pg_420_522_07054f960e6a5d42660af2bdda2fcc0a26120d71", "taxonomy" ],
      "nodeid" : 697188,
      "taxRank" : "no rank",
      "nleaves" : 2
    } ],
    "name" : "Neognathae",
    "ottId" : "241846",
    "supportedBy" : [ "taxonomy" ],
    "nodeid" : 696811,
    "taxRank" : "superorder",
    "nleaves" : 5
  } ],
  "maxnodedepth" : 3,
  "nTipDescendants" : 14513,
  "nleaves" : 8,
  "taxSource" : "ncbi:8782,worms:1836,gbif:212,irmng:1142",
  "taxRank" : "class",
  "ottId" : "81461",
  "pathToRoot" : [ {
    "supporting_sources" : [ "taxonomy" ],
    "uniqname" : "Coelurosauria",
    "taxSource" : "ncbi:436492",
    "name" : "Coelurosauria",
    "ottId" : "664351",
    "nodeid" : 696700,
    "taxRank" : "no rank"
  }, {
    "supporting_sources" : [ "taxonomy" ],
    "uniqname" : "Theropoda",
    "taxSource" : "ncbi:436491",
    "name" : "Theropoda",
    "ottId" : "664350",
    "nodeid" : 696699,
    "taxRank" : "no rank"
  }, {
    "supporting_sources" : [ "taxonomy" ],
    "uniqname" : "Saurischia",
    "taxSource" : "ncbi:436489,irmng:10565",
    "name" : "Saurischia",
    "ottId" : "90223",
    "nodeid" : 696698,
    "taxRank" : "order"
  }, {
    "supporting_sources" : [ "taxonomy" ],
    "uniqname" : "Dinosauria",
    "taxSource" : "ncbi:436486",
    "name" : "Dinosauria",
    "ottId" : "90215",
    "nodeid" : 696697,
    "taxRank" : "no rank"
  }, {
    "supporting_sources" : [ "taxonomy" ],
    "uniqname" : "Archosauria",
    "taxSource" : "ncbi:8492",
    "name" : "Archosauria",
    "ottId" : "335588",
    "nodeid" : 696696,
    "taxRank" : "no rank"
  }, {
    "supporting_sources" : [ "taxonomy" ],
    "uniqname" : "Archelosauria",
    "taxSource" : "ncbi:1329799",
    "name" : "Archelosauria",
    "ottId" : "4947372",
    "nodeid" : 696695,
    "taxRank" : "no rank"
  }, {
    "supporting_sources" : [ "taxonomy" ],
    "uniqname" : "Sauria (order in phylum Opisthokonta)",
    "taxSource" : "ncbi:32561,worms:342632",
    "name" : "Sauria",
    "ottId" : "329823",
    "nodeid" : 684049,
    "taxRank" : "order"
  }, {
    "supporting_sources" : [ "taxonomy" ],
    "uniqname" : "Sauropsida",
    "taxSource" : "ncbi:8457",
    "name" : "Sauropsida",
    "ottId" : "639642",
    "nodeid" : 684048,
    "taxRank" : "no rank"
  }, {
    "supporting_sources" : [ "taxonomy" ],
    "uniqname" : "Amniota",
    "taxSource" : "ncbi:32524",
    "name" : "Amniota",
    "ottId" : "229560",
    "nodeid" : 672086,
    "taxRank" : "no rank"
  }, {
    "supporting_sources" : [ "taxonomy" ],
    "uniqname" : "Tetrapoda (superclass in Deuterostomia)",
    "taxSource" : "ncbi:32523,worms:1831",
    "name" : "Tetrapoda",
    "ottId" : "229562",
    "nodeid" : 672085,
    "taxRank" : "superclass"
  }, {
    "supporting_sources" : [ "taxonomy" ],
    "uniqname" : "Dipnotetrapodomorpha",
    "taxSource" : "ncbi:1338369",
    "name" : "Dipnotetrapodomorpha",
    "ottId" : "4940726",
    "nodeid" : 672084,
    "taxRank" : "no rank"
  }, {
    "supporting_sources" : [ "taxonomy" ],
    "uniqname" : "Sarcopterygii",
    "taxSource" : "ncbi:8287,worms:163509,gbif:238,irmng:1531",
    "name" : "Sarcopterygii",
    "ottId" : "458402",
    "nodeid" : 672076,
    "taxRank" : "class"
  }, {
    "supporting_sources" : [ "taxonomy" ],
    "uniqname" : "Euteleostomi",
    "taxSource" : "ncbi:117571",
    "name" : "Euteleostomi",
    "ottId" : "114654",
    "nodeid" : 672075,
    "taxRank" : "no rank"
  }, {
    "supporting_sources" : [ "taxonomy" ],
    "uniqname" : "Teleostomi",
    "taxSource" : "ncbi:117570",
    "name" : "Teleostomi",
    "ottId" : "114656",
    "nodeid" : 672074,
    "taxRank" : "no rank"
  }, {
    "supporting_sources" : [ "taxonomy" ],
    "uniqname" : "Gnathostomata (superclass in phylum Chordata)",
    "taxSource" : "ncbi:7776,worms:1828",
    "name" : "Gnathostomata",
    "ottId" : "278114",
    "nodeid" : 672073,
    "taxRank" : "superclass"
  }, {
    "supporting_sources" : [ "taxonomy" ],
    "uniqname" : "Vertebrata (subphylum in phylum Opisthokonta)",
    "taxSource" : "ncbi:7742,worms:146419",
    "name" : "Vertebrata",
    "ottId" : "801601",
    "nodeid" : 672072,
    "taxRank" : "subphylum"
  }, {
    "supporting_sources" : [ "pg_2710_6291_a2c48df995ddc9fd208986c3d4225112550c8452", "taxonomy" ],
    "uniqname" : "Craniata (subphylum in Deuterostomia)",
    "taxSource" : "ncbi:89593",
    "name" : "Craniata",
    "ottId" : "947318",
    "nodeid" : 672071,
    "taxRank" : "subphylum"
  }, {
    "supporting_sources" : [ "pg_2710_6291_a2c48df995ddc9fd208986c3d4225112550c8452", "taxonomy" ],
    "nodeid" : 2596460
  }, {
    "supporting_sources" : [ "pg_2710_6291_a2c48df995ddc9fd208986c3d4225112550c8452", "taxonomy" ],
    "uniqname" : "Chordata",
    "taxSource" : "ncbi:7711,worms:1821,gbif:44,irmng:148",
    "name" : "Chordata",
    "ottId" : "125642",
    "nodeid" : 672023,
    "taxRank" : "phylum"
  }, {
    "supporting_sources" : [ "pg_2710_6291_a2c48df995ddc9fd208986c3d4225112550c8452", "taxonomy" ],
    "uniqname" : "Deuterostomia",
    "taxSource" : "ncbi:33511",
    "name" : "Deuterostomia",
    "ottId" : "147604",
    "nodeid" : 660602,
    "taxRank" : "no rank"
  }, {
    "supporting_sources" : [ "pg_2710_6291_a2c48df995ddc9fd208986c3d4225112550c8452", "taxonomy" ],
    "nodeid" : 2596194
  }, {
    "supporting_sources" : [ "pg_2710_6291_a2c48df995ddc9fd208986c3d4225112550c8452", "taxonomy" ],
    "uniqname" : "Bilateria",
    "taxSource" : "ncbi:33213",
    "name" : "Bilateria",
    "ottId" : "117569",
    "nodeid" : 659934,
    "taxRank" : "no rank"
  }, {
    "supporting_sources" : [ "pg_2710_6291_a2c48df995ddc9fd208986c3d4225112550c8452", "taxonomy" ],
    "nodeid" : 2706113
  }, {
    "supporting_sources" : [ "pg_2710_6291_a2c48df995ddc9fd208986c3d4225112550c8452", "taxonomy" ],
    "nodeid" : 2706112
  }, {
    "supporting_sources" : [ "pg_2710_6291_a2c48df995ddc9fd208986c3d4225112550c8452", "taxonomy" ],
    "nodeid" : 2706111
  }, {
    "supporting_sources" : [ "pg_2822_6569_a2c48df995ddc9fd208986c3d4225112550c8452", "taxonomy", "pg_2710_6291_a2c48df995ddc9fd208986c3d4225112550c8452" ],
    "uniqname" : "Metazoa",
    "taxSource" : "silva:D14357/#4,ncbi:33208,worms:2,gbif:1,irmng:11",
    "name" : "Metazoa",
    "ottId" : "691846",
    "nodeid" : 659739,
    "taxRank" : "kingdom"
  }, {
    "supporting_sources" : [ "pg_2822_6569_a2c48df995ddc9fd208986c3d4225112550c8452", "taxonomy" ],
    "nodeid" : 2692390
  }, {
    "supporting_sources" : [ "taxonomy", "pg_2822_6569_a2c48df995ddc9fd208986c3d4225112550c8452" ],
    "uniqname" : "Holozoa",
    "taxSource" : "silva:D14357/#3",
    "name" : "Holozoa",
    "ottId" : "5246131",
    "nodeid" : 659514,
    "taxRank" : "no rank"
  }, {
    "supporting_sources" : [ "taxonomy" ],
    "uniqname" : "Opisthokonta",
    "taxSource" : "silva:D11377/#2,ncbi:33154,irmng:183",
    "name" : "Opisthokonta",
    "ottId" : "332573",
    "nodeid" : 356355,
    "taxRank" : "phylum"
  }, {
    "supporting_sources" : [ "taxonomy", "pg_2644_6164_a2c48df995ddc9fd208986c3d4225112550c8452" ],
    "uniqname" : "Eukaryota",
    "taxSource" : "silva:D11377/#1,ncbi:2759",
    "name" : "Eukaryota",
    "ottId" : "304358",
    "nodeid" : 3,
    "taxRank" : "domain"
  }, {
    "supporting_sources" : [ "taxonomy" ],
    "uniqname" : "cellular organisms",
    "taxSource" : "ncbi:131567",
    "name" : "cellular organisms",
    "ottId" : "93302",
    "nodeid" : 1,
    "taxRank" : "no rank"
  } ],
  "supportedBy" : [ "taxonomy" ],
  "sourceToMetaMap" : {
    "pg_2710_6291_a2c48df995ddc9fd208986c3d4225112550c8452" : {
      "git_sha" : "a2c48df995ddc9fd208986c3d4225112550c8452",
      "tree_id" : "6291",
      "study_id" : "pg_2710"
    },
    "pg_2822_6569_a2c48df995ddc9fd208986c3d4225112550c8452" : {
      "git_sha" : "a2c48df995ddc9fd208986c3d4225112550c8452",
      "tree_id" : "6569",
      "study_id" : "pg_2822"
    },
    "pg_420_522_07054f960e6a5d42660af2bdda2fcc0a26120d71" : {
      "git_sha" : "07054f960e6a5d42660af2bdda2fcc0a26120d71",
      "tree_id" : "522",
      "study_id" : "pg_420"
    },
    "pg_2926_6757_a2c48df995ddc9fd208986c3d4225112550c8452" : {
      "git_sha" : "a2c48df995ddc9fd208986c3d4225112550c8452",
      "tree_id" : "6757",
      "study_id" : "pg_2926"
    },
    "taxonomy" : {
      "version" : "ott2.9draft8"
    }
  }
}
```

**Comment by jimallman** [comment]
I see that you’ve retained the **nLeaves** field for all nodes. We could drop it for all but the topmost (target) node, but I can imagine it proving useful for speeding up the drawing/layout code in argus. So let's keep this (in all nodes) for now.

**Comment by jar398** [comment]
This is great, thanks.

I think having the information for all nodes is useful. The number ought to
be displayed in the UI, for example in the taxon information panel.  It
could also feed into the tree display somehow, maybe influencing the size
of the bubble.

For taxa that are terminal in the viewed slice, one should be able to tell
visually whether there are non-displayed descendants or not. nLeaves > 0
(or > 1?) provides this information.

I can file issues for these features separately; my purpose here was just
to defend the presence of nLeaves at every node.

**Comment by jimallman** [comment]
> I think having the information for all nodes is useful. The number ought to be displayed in the UI, for example in the taxon information panel.  It could also feed into the tree display somehow, maybe influencing the size of the bubble.

Agreed on all counts, but to clarify, this is all covered by the new `nTipDescendants` field. It's the old `nLeaves` field (which just counts nodes in the current argus view) that I thought we might want to drop for all but the main/target node. I withdrew that request in any case, since it might still come in handy for faster drawing in argus.

**Comment by jar398** [comment]
Sorry!  Again joining in without reading carefully

**Comment by jimallman** [comment]
@josephwb, I see that `nTipDescendants` includes the current node, so for a tip nleaves=0, nTipDescendants=1. No problem, except that it makes it impossible to distinguish between a true tip and a knuckle (an internal node with just one descendant) whose only descendant is a tip.

Can we exclude the current node from nTipDescendants?

**Comment by josephwb** [comment]
Can do. Just have to check:
if not internal:
  nTipDescendants = 0
Will do this in a bit; running around to do HR stuff.

**Comment by josephwb** [comment]
@jimallman I think c630ecc57561f514c362be7fbeb3cdbed5b0151c covers this.

**Comment by jimallman** [comment]
Thanks @josephwb!

**Pull request merged**
