### PR TITLE
update flags, and stuff to help automation

### PR DESCRIPTION
**Pull request by josephwb**

### CODE REVIEW

**Comment by jar398** [comment]
Having the list of flags be repeated seems to be just asking for trouble.
If it were my I would put the list in a file so it could be read by any
processor that needs it.

Also I don't see why the 2.8 and 2.9 lists need to be kept separate. Why
not just a single list that is the union of all flags to be hiding-inducers
across all taxonomy versions? I sincerely doubt that a single flag will be
a hider in one OTT version and not in another.

**Comment by josephwb** [comment]
I kept the 2.8 and 2.9 lists separate for 1) backwards compatibility and 2) enable the replication of the published synthetic tree. Putting the list in a separate file is fine; I was just updating the existing code.

**Comment by josephwb** [comment]
Maybe distribute a file listing "dubious" flags with the taxonomy distribution? This would keep all things together, and initializing the graph is made simple just be referring to an OTT directory.

**Comment by josephwb** [comment]
But the code here is definitely an improvement to the older code, and is allowing me to do thesynthesis testing, so I think we should go ahead and incorporate it while we discuss possible refactoring. Right?

**Comment by jar398** [comment]
Sure.

We have to expunge all use of the word "dubious". It is not descriptive. We
have taxa that are hidden (or suppressed) for purposes of synthesis, and we
have flags that lead to them becoming so. The word "dubious" was used early
on, in jest, for want of a better word. We have a better word now.

The initial idea of the flags system was that the use of the flags would be
application specific, so that the decision as to what was to be hidden
belonged to treemachine, not to the taxonomy. That is why the taxonomy does
not take a stand on what is to be hidden or not, or maintain the list of
applicable flags.

On the other hand, there are places where it is very useful for smasher to
know what's to be hidden, in particular for regression testing (we don't
want non-hidden taxa to become hidden without knowing why), so it has
replicated treemachine's idea of hiddenness for that purpose. So one could
argue for either subsystem as the host of the hidden-inducing flags.

**Pull request merged**
