### PR TITLE
update filter flags

### PR DESCRIPTION
**Pull request by josephwb**
Add "merged" and "inconsistent" to the set of flags to filter.

### CODE REVIEW

**Comment by josephwb** [comment]
That last commit is not relevant to flags, but is relevant to preparing inputs for decomposition.

**Comment by jar398** [comment]
Looks good. Is it deployed to devapi?

**Comment by josephwb** [comment]
Everything except the last commit, but it has nothing to do with the DB or plugins, so it is safe.

**Comment by josephwb** [comment]
Deploying now to be extra safe.

**Comment by josephwb** [comment]
Ok, my checks pass.

**Pull request merged**
