### PR TITLE
Reduce logging

### PR DESCRIPTION
**Pull request by josephwb**
Cuts down on superfluous logging, and reports timestamps, arguments, and service success (as per issue #162). This is currently deployed on dev.

### CODE REVIEW

**Comment by josephwb** [comment]
All tests run fine on dev. Not sure why travis is failing, and I don't know how to re-run it.

**Comment by josephwb** [comment]
Travis seems to be dying here:
```
...
mv: cannot stat `gcmdr/example/asterales_synth.db': No such file or directory
The command "./travis-config/setup_db.sh" failed and exited with 1 during .
Your build has been stopped.
```
which has nothing to do with the code chages...

**Comment by josephwb** [comment]
Okay, found the reason travis failed: gcmdr was pulling studies from devapi instead of api; one tree ([3959 for source pg_1944](https://tree.opentreeoflife.org/curator/study/view/pg_1944/?tab=trees&tree=tree3959)) is apparently not available on devapi.

**Comment by josephwb** [comment]
Ok, done for reals. All yours @jar398. Deployed on dev. I checked the console.log there and everything looks as it should.

**Comment by jar398** [comment]
Thanks!

**Pull request merged**
